monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.usb-Generic_USB_Audio-00.HiFi__Headphones__sink"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 1200
        priority.session = 1200
      }
    }
  }
]
monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "bluez_output.04_57_91_39_60_3A.1"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 1300
        priority.session = 1300
      }
    }
  }
  {
    matches = [
      {
        node.name = "bluez_output.94_DB_56_E0_A0_1B.1"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 1300
        priority.session = 1300
      }
    }
  }
]
